name: Deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
      branches: [main]
      types: [opened, synchronize]
      
env:
    MONGODB_URI: ${{ secrets.MONGODB_URI }}
    TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    SECRET: ${{ secrets.SECRET }}
    PORT: 3000

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
            - name: Install dependencies
              if: ${{ steps.cache.outcome != 'true' }}
              run: npm ci
            - name: Lint code
              run: npm run eslint
            - name: Run tests
              run: npm test

    deploy:
      needs: test
      name: Deploy app
      runs-on: ubuntu-latest
      concurrency: deploy-group    
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}