name: Deployment pipeline

on:
    push:
        branches:
            - main
env:
    MONGODB_URI: ${{ secrets.MONGODB_URI }}
    TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    SECRET: ${{ secrets.SECRET }}
    PORT: 3000

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Cache dependencies
              id: cache
              uses: actions/cache@v4
              with:
                path: node_modules
                key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
            - name: Install dependencies
              if: ${{ steps.cache.outcome != 'true' }}
              run: npm ci
            - name: Run tests
              run: npm test

